INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10001, 'in28Minutes', 'Learn AWS', CURRENT_DATE(), false);

INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10002, 'in28Minutes', 'Learn Devops', CURRENT_DATE(), false);

INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10003, 'in28Minutes', 'Learn Full Stack Developer', CURRENT_DATE(), false);

INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10004, 'in28Minutes', 'Learn Spring Boot', CURRENT_DATE(), false);