INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10001, 'in28Minutes', 'Learn AWS - h2', CURRENT_DATE(), false);

INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10002, 'in28Minutes', 'Learn Devops - h2', CURRENT_DATE(), false);

INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10003, 'in28Minutes', 'Learn Full Stack Developer - h2', CURRENT_DATE(), false);

INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10004, 'in28Minutes', 'Learn Spring Boot - h2', CURRENT_DATE(), false);